project_id = "fhsjhoygllcchfinalih"

[functions.import-airtable-leads]
verify_jwt = false

[functions.dedupe-leads]
verify_jwt = true

[functions.add-booking]
verify_jwt = false

[functions.upsert-new-patients]
verify_jwt = false